all:
  hosts:
    albert:
      ansible_host: 192.168.122.222
      ip: 192.168.122.222
      access_ip: 192.168.122.222
  children:
    kube-master:
      hosts:
        albert:
    kube-node:
      hosts:
        albert:
    etcd:
      hosts:
        albert:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
