all:
  hosts:
    albert:
      ansible_host: 104.168.45.226
      ip: 104.168.45.226
      access_ip: 104.168.45.226
  children:
    kube-master:
      hosts:
        albert:
    kube-node:
      hosts:
        albert:
    etcd:
      hosts:
        albert:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
